### ISSUE TITLE
[Question] Easy differentiation between RndmForest Scikit-learn and pure-predict upon loading

### ISSUE THREAD

**Issue by JensBlack** [Ibotta/pure-predict#14]
Hi,

great package! I really like the simplicity and the speed improvement.

I have users that would like to be able to use both "versions" of the classifier and I would like to find an easy way to differentiate between the two directly after loading them.

so far I came up with based on it's object description:

```

    with open(path_to_sav,"rb") as f:
        clf= pickle.load(f)
    if 'pure' in str(clf):
       print(clf)

Output:
<pure_sklearn.ensemble._forest.RandomForestClassifierPure object at 0x00000201490EEF98>
```
Is there a better way to do this?

**Comment by denver1117** [comment]
I think what you are doing seems reasonable 💯
