### ISSUE TITLE
Cannot find 'pure_sklearn' counterpart for ColumnTransformer

### ISSUE THREAD

**Issue by chethan-avyay** [Ibotta/pure-predict#16]
convert_estimator giving value error if I use for sklearn pipeline <br>
`` pipe = convert_estimator(pipe) `` <br>
i used above code for pipeline and I got below error <b>
![image](https://user-images.githubusercontent.com/76741966/114157217-09b96100-9941-11eb-8ad3-7653300d9a49.png)

**Comment by denver1117** [comment]
Yes unfortunately this transformer isn't supported. By design, pure predict only supports a subset of sklearn estimators and transformers. Please feel free to contribute.
