### ISSUE TITLE
error when using using convert_estimator with MultiOutputRegressor

### ISSUE THREAD

**Issue by nrchade** [Ibotta/pure-predict#17]
**Describe the bug**
ValueError: Cannot find 'pure_sklearn' counterpart for MultiOutputRegressor

**To Reproduce**
Convert a pickled MultiOutputRegressor model to pure_sklearn using:
model = pickle.load(filename, 'rb')
model = convert_estimator(model)

**Expected behavior**
Expected conversion to pure_sklearn version

**Additional context**

**Comment by denver1117** [comment]
Yes unfortunately this meta-estimator isn't supported. By design, pure predict only supports a subset of sklearn estimators and meta-estimators. Please feel free to contribute.
