### ISSUE TITLE
Question about pure predict

### ISSUE THREAD

**Issue by staebchen0** [Ibotta/pure-predict#6]
hi, i have a question about pure predict. I am still new to the field and am looking for a way to speed up the prediction of my program (python 3.7 under Windwos). I saved the model in an hdf5 file. My laptop, on which the program runs, has only 8 ram RAM

Call of the predict function
`ippreds = model.predict (np.expand_dims (ipframe, axis = 0)) [0]`

for me the prediction takes an average of 13-15 milliseconds

> [INFO] Start Predict..Sun Apr  5 18:15:12 2020
> [INFO] Finish Predict..Sun Apr  5 18:15:12 2020
> Time Total: 0:00:00.155961
> 
> [INFO] Start Predict..Sun Apr  5 18:15:12 2020
> [INFO] Finish Predict..Sun Apr  5 18:15:12 2020
> Time Total: 0:00:00.152110
> 
> [INFO] Start Predict..Sun Apr  5 18:15:12 2020
> [INFO] Finish Predict..Sun Apr  5 18:15:13 2020
> Time Total: 0:00:00.148105

could I improve the result with Pure Predict?

Many thanks in advance
Anja

**Comment by denver1117** [comment]
This depends on the type of model and the size of the input array for prediction. If that numpy array has low dimensionality and/or small number of rows, it could very well be sped up.
